### ISSUE TITLE
Wrong Tangle referenced by Navrey

### ISSUE THREAD

**Issue by NFlieger** [ServUO/ServUO#399] opened 2016-02-10 15:38 UTC
Hi,

i am not certain if this is the right way you want bugs to be reported, but i found one and want to share it with you.

Navrey Night-Eyes should drop the Half Apron Tangle, which is currently not the case.

Navrey (\scripts\mobiles\underworld\navery\navrey.cs) uses Server.Mobiles.Tangle instead of Server.Items.Tangle1 in line 14, since Tangle1 is the half apron and Tangle is the named swamp monster.

**Comment by qbradq** [comment] 2016-02-11 03:22
Duplicate of #402

**Closed by qbradq** 2016-02-11 03:22 UTC
