### ISSUE TITLE
OSX - "ServUO.MONO.exe": System.ArgumentException: Path is empty

### ISSUE THREAD

**Issue by tylerssn** [ServUO/ServUO#3255] opened 2018-03-27 17:48 UTC
With mono installed, I cloned the ServUO repo and executed `make`. The compiler appears to work but when the script attempts to execute the `ServUO.MONO.exe`, I get the following output:
```
`pwd`/ServUO.sh
----------
ServUO - [https://www.servuo.com] Version 0.5, Build 6660.24172 - Release
Core: Running with arguments: -noconsole
Core: Optimizing for 8 64-bit processors
Core: Compiled for .NET MONO/CSC/Unknown
Core: Unix environment detected
RandomImpl: SimpleRandom (Software)
Core: Loading config...
Scripts: Compiling C# scripts...Error:
System.ArgumentException: Path is empty
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x00027] in <6e9b92f0d119424382ef180639777acb>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) [0x00000] in <6e9b92f0d119424382ef180639777acb>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
  at System.IO.File.OpenRead (System.String path) [0x00000] in <6e9b92f0d119424382ef180639777acb>:0 
  at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromFileBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames) [0x00023] in <ff7a04492e6542e89795ad0b4ef278b5>:0 
  at System.CodeDom.Compiler.CodeDomProvider.CompileAssemblyFromFile (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames) [0x00006] in <ff7a04492e6542e89795ad0b4ef278b5>:0 
  at Server.ScriptCompiler.CompileCSScripts (System.Boolean debug, System.Boolean cache, System.Reflection.Assembly& assembly) [0x001c8] in <0efab05b2c164ba695fc6d002e965c44>:0 
  at Server.ScriptCompiler.Compile (System.Boolean debug, System.Boolean cache) [0x00034] in <0efab05b2c164ba695fc6d002e965c44>:0 
  at Server.Core.Main (System.String[] args) [0x005d9] in <0efab05b2c164ba695fc6d002e965c44>:0 
This exception is fatal, press return to exit

/Users/tyler/path/servuo/ServUO.sh: line 2: 15857 Killed: 9               mono /Users/tyler/path/servuo/ServUO.MONO.exe
make: *** [run] Error 137
```

I can't find any configuration instructions but I assume I need to point to UO maps and other data. Is that what I am missing here?

**Comment by Xeroxxx** [comment] 2018-03-27 17:57
This issue is known and will be fixed with this commit.

https://github.com/ServUO/ServUO/pull/3250

**Comment by tylerssn** [comment] 2018-03-27 17:59
Thanks for the quick response. I'm excited to give this a go. Is the immediate fix to rollback to a previous Mono version. If so, which?

**Comment by tylerssn** [comment] 2018-03-27 18:21
Additionally, I checked out the commit you referenced and executed `make`. It errors with the following:

```
ServUO - [https://www.servuo.com] Version 0.5, Build 6660.25638 - Release
Core: Running with arguments: -noconsole
Core: Optimizing for 8 64-bit processors
Core: Compiled for MONO 5.4.1.6 (tarball Mon Dec 11 14:59:42 GMT 2017)
Core: Unix environment detected
RandomImpl: SimpleRandom (Software)
Core: Loading config...
Scripts: Compiling C# scripts...Error:
System.Exception: Compiler failed to produce the assembly. Output: ''
  at Microsoft.CSharp.CSharpCodeGenerator.FromFileBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames) [0x002d1] in <ff7a04492e6542e89795ad0b4ef278b5>:0 
  at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromFileBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames) [0x0003a] in <ff7a04492e6542e89795ad0b4ef278b5>:0 
  at System.CodeDom.Compiler.CodeDomProvider.CompileAssemblyFromFile (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames) [0x00006] in <ff7a04492e6542e89795ad0b4ef278b5>:0 
  at Server.ScriptCompiler.CompileCSScripts (System.Boolean debug, System.Boolean cache, System.Reflection.Assembly& assembly) [0x001d2] in <fbcc2db656e64ef79ac64c108fc7388b>:0 
  at Server.ScriptCompiler.Compile (System.Boolean debug, System.Boolean cache) [0x00034] in <fbcc2db656e64ef79ac64c108fc7388b>:0 
  at Server.Core.Main (System.String[] args) [0x00648] in <fbcc2db656e64ef79ac64c108fc7388b>:0 
This exception is fatal, press return to exit

/Users/tyler/path/servuo/ServUO.sh: line 2: 59232 Killed: 9               mono /Users/tyler/path/servuo/ServUO.MONO.exe
make: *** [run] Error 137
```

**Comment by tylerssn** [comment] 2018-03-29 17:16
OSX continues to throw various errors at me, so for now, I am building and running ServUO through a Linux Docker container.

**Comment by Xeroxxx** [comment] 2018-03-29 22:42
Can you add the various error you get?

Mono is installed via brew? Which OSX Version?

**Comment by DarkLotus** [comment] 2018-03-30 02:27
checkout the commit in #3250 
You only need to change the one line in ScriptCompiler and it should solve the issue.

**Comment by Xeroxxx** [comment] 2018-03-30 09:15
He said he did that. I'm going to verify this on my OSX.

However #3250 fixes MONO for Linux.

**Comment by DarkLotus** [comment] 2018-03-30 10:01
Your right, Im not sure what the issue is, I just tested locally on osx 10.13/mono 5.8.10 and there's no more information, just the blank output.

**Comment by Xeroxxx** [comment] 2018-03-30 13:01
Thats a really strange behavior of MONO on OSX. I can reproduce this but cant figure out what exactly is causing the problem.

However the initial bug report is been fixed with my commit for OSX and Linux.

Its no permission issue or an issue with path or string arrays.

**Comment by DarkLotus** [comment] 2018-03-30 13:45
It's not an issue with any of the references either, modifying that has no effect.
However I can compile successfully if i replace Scripts with a dummy folder with just a handful of scripts, but it's hard to split the Scripts project up to narrow it down much more than that. I also tried swapping over to the Roslyn codedom nuget with no luck.

**Comment by Xeroxxx** [comment] 2018-03-30 18:00
I may investigate this later. mono on osx specific error....

**Closed** 2018-04-06 21:50 UTC

**Comment by akhodakivskiy** [comment] 2018-04-22 17:57
Is this really resolved? I'm still getting this error while runnign ServUO.exe:

```
$ ./ServUO.sh
----------
ServUO - [https://www.servuo.com] Version 0.5, Build 6686.37417 - Release
Core: Running with arguments: -noconsole
Core: Optimizing for 4 64-bit processors
Core: Unix environment detected
Core: Compiled for MONO and running on 5.10.1.49 (2017-12/75be2e65371 Fri Apr 20 17:19:14 EDT 2018)
RandomImpl: SimpleRandom (Software)
Core: Loading config...
Scripts: Compiling C# scripts...Error:
System.Exception: Compiler failed to produce the assembly. Output: ''
  at Microsoft.CSharp.CSharpCodeGenerator.FromFileBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames) [0x002d1] in <f8bb3922e51744d9ace1aa6aedc374ea>:0
  at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromFileBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames) [0x0003a] in <f8bb3922e51744d9ace1aa6aedc374ea>:0
  at System.CodeDom.Compiler.CodeDomProvider.CompileAssemblyFromFile (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames) [0x00006] in <f8bb3922e51744d9ace1aa6aedc374ea>:0
  at Server.ScriptCompiler.CompileCSScripts (System.Boolean debug, System.Boolean cache, System.Reflection.Assembly& assembly) [0x001d2] in <0d2650adba76404bb5ca3ad1f661af83>:0
  at Server.ScriptCompiler.Compile (System.Boolean debug, System.Boolean cache) [0x00034] in <0d2650adba76404bb5ca3ad1f661af83>:0
  at Server.Core.Main (System.String[] args) [0x00621] in <0d2650adba76404bb5ca3ad1f661af83>:0
This exception is fatal, press return to exit
```
